spring:
  application:
    name: system
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: SportSystemPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          starttls.required: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  port: 8086

jwt:
  signerKey: "3m47O+gM3Sc0lc9I5pMhfGFZMoqvbFtLoNs6Lmq9nOg="
  valid-duration: 360000
  refreshable-duration: 36000

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK}

momo:
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  endpoint: ${MOMO_ENDPOINT}
  redirect-url: ${MOMO_RETURN_URL}
  ipn-url: ${MOMO_IPN_URL}
  request-type: captureWallet
  lang: vi
